import { PlanPaymentType } from "@/modules/subscriptions/enums/plan-payment-type.enum";

export const SUBSCRIPTION_PLANS = [
	// Individual subscription plans
	{
		name: "Basic Shield",
		tier: 1,
		accountType: "individual" as const,
		paymentType: PlanPaymentType.SUBSCRIPTION,
		amount: 5000000, // ₦50,000 in kobo
		currency: "NGN",
		interval: "monthly",
		paystackPlanCode: "PLN_zpdclk6rfprabvh",
		description: "For everyday phone & social media users",
		features: [
			"Incident reporting via phone/email",
			"Social media account recovery",
			"Basic scam & fraud advisory",
			"Personal data privacy checks",
			"1 cyber incident resolution / month",
			"24–48 hrs response time",
		],
		maxIncidents: 1,
		active: true,
	},
	{
		name: "Safe Guard",
		tier: 2,
		accountType: "individual" as const,
		paymentType: PlanPaymentType.SUBSCRIPTION,
		amount: 8000000, // ₦80,000 in kobo
		currency: "NGN",
		interval: "monthly",
		paystackPlanCode: "PLN_n6ncggceegkbhbt",
		description: "For freelancers, small-scale sellers, influencers",
		features: [
			"Priority incident handling",
			"Malware & spyware removal",
			"Payment fraud investigation",
			"Social media & email breach recovery",
			"Data loss prevention tips",
			"Up to 2 incidents resolved / month",
			"12–24 hrs response time",
		],
		maxIncidents: 2,
		active: true,
	},
	{
		name: "Total Lockdown",
		tier: 3,
		accountType: "individual" as const,
		paymentType: PlanPaymentType.SUBSCRIPTION,
		amount: 10000000, // ₦100,000 in kobo
		currency: "NGN",
		interval: "monthly",
		paystackPlanCode: "PLN_ki46lweo54uhej3",
		description: "For high-risk individuals, public figures, executives",
		features: [
			"24/7 priority access",
			"Advanced account monitoring",
			"Comprehensive breach investigation",
			"Device security optimization",
			"Data recovery support",
			"3 incidents resolution / month",
			"4–6 hrs response time",
		],
		maxIncidents: 3,
		active: true,
	},
	// Organization subscription plans
	{
		name: "Business Shield",
		tier: 1,
		accountType: "organization" as const,
		paymentType: PlanPaymentType.SUBSCRIPTION,
		amount: 15000000, // ₦150,000 in kobo
		currency: "NGN",
		interval: "monthly",
		paystackPlanCode: "PLN_nt6nyw5q6e7ck85",
		description: "For small businesses (1–10 staff)",
		features: [
			"Incident reporting hotline",
			"Phishing & scam prevention",
			"Basic ransomware & malware response",
			"Website & email breach recovery",
			"2 cyber incident resolution / month",
			"24–48 hrs response time",
		],
		maxIncidents: 2,
		active: true,
	},
	{
		name: "Enterprise Guard",
		tier: 2,
		accountType: "organization" as const,
		paymentType: PlanPaymentType.SUBSCRIPTION,
		amount: 25000000, // ₦250,000 in kobo
		currency: "NGN",
		interval: "monthly",
		paystackPlanCode: "PLN_eahyxv6lbjktbjq",
		description: "For medium-sized businesses (11–50 staff)",
		features: [
			"Dedicated account manager",
			"Network intrusion detection",
			"Ransomware containment & removal",
			"DDoS attack mitigation",
			"Payment system compromise investigation",
			"Up to 5 incidents resolved / month",
			"12–24 hrs response time",
		],
		maxIncidents: 5,
		active: true,
	},
	{
		name: "Corporate Fortress",
		tier: 3,
		accountType: "organization" as const,
		paymentType: PlanPaymentType.SUBSCRIPTION,
		amount: 50000000, // ₦500,000 in kobo
		currency: "NGN",
		interval: "monthly",
		paystackPlanCode: "PLN_xosan7dk1d2vxnt",
		description: "For large corporations & critical sectors",
		features: [
			"24/7 SOC (Security Operations Center) support",
			"Onsite & remote incident response",
			"Insider threat detection",
			"Advanced threat hunting & forensics",
			"Unlimited incidents / month",
			"SLA: under 4 hrs response time",
		],
		maxIncidents: null,
		active: true,
	},
	// Example pay-as-you-go products (admin can create more via API)
	{
		name: "Pay As You Go",
		tier: 0,
		accountType: "individual" as const,
		paymentType: PlanPaymentType.ONE_TIME,
		amount: 2500000, // ₦25,000 in kobo
		currency: "NGN",
		interval: null,
		paystackPlanCode: null,
		description: "One-time incident response — pay only when you need help",
		features: [
			"Single cyber incident resolution",
			"No monthly commitment",
			"Incident reporting via phone/email",
			"24–48 hrs response time",
		],
		maxIncidents: 1,
		active: true,
	},
	{
		name: "Pay As You Go Business",
		tier: 0,
		accountType: "organization" as const,
		paymentType: PlanPaymentType.ONE_TIME,
		amount: 7500000, // ₦75,000 in kobo
		currency: "NGN",
		interval: null,
		paystackPlanCode: null,
		description:
			"One-time business incident response — pay per incident without a subscription",
		features: [
			"Single cyber incident resolution",
			"No monthly commitment",
			"Incident reporting hotline",
			"24–48 hrs response time",
		],
		maxIncidents: 1,
		active: true,
	},
];
