import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1789648491657 implements MigrationInterface {
    name = 'InitialSchema1789648491657'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "last_login" character varying, "avatar" jsonb, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_sub_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "category_id" uuid, CONSTRAINT "PK_5c6053949d9faeb3133546f80e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, CONSTRAINT "PK_41d5bc6539e69677fb5f54fd80d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tickets" ("ticket_id" character varying NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "status" character varying NOT NULL DEFAULT 'CREATED', "severity" character varying, "tier" character varying, "location" character varying NOT NULL, "victim_information" jsonb, "attachments" character varying array, "reporterName" character varying NOT NULL, "contact_information" jsonb, "internal_notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT 'NOW()', "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(), "created_by_user_id" uuid, "assigned_responder_id" uuid, "ticket_category_id" uuid, "ticket _sub_category_id" uuid, CONSTRAINT "PK_8de0cebd669ff84059e9976e17d" PRIMARY KEY ("ticket_id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_lifecycle" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "action" character varying NOT NULL, "notes" text, "ticket_id" character varying, "performed_by_user_id" uuid, CONSTRAINT "PK_12a7b09883544868b8dd9536601" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "individual_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "phone_number" character varying NOT NULL, "profile_picture" character varying, "user_id" uuid, CONSTRAINT "REL_43bcca0b3b3a7422f9fc7a7547" UNIQUE ("user_id"), CONSTRAINT "PK_ae930da8955aff26556a4095dca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organization_name" character varying NOT NULL, "logo_url" character varying, "industry_type" character varying NOT NULL, "company_size" character varying NOT NULL, "business_address" character varying NOT NULL, "city" character varying NOT NULL, "state" character varying NOT NULL, "country" character varying NOT NULL, "phone_number" character varying NOT NULL, "primary_contact_first_name" character varying NOT NULL, "primary_contact_last_name" character varying NOT NULL, "primary_contact_job_title" character varying NOT NULL, "primary_contact_email" character varying NOT NULL, "primary_contact_phone_number" character varying NOT NULL, "user_id" uuid, CONSTRAINT "REL_762b77719a1ebc06bc35af0296" UNIQUE ("user_id"), CONSTRAINT "PK_db74d09512f13d2218cebd8e1eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5650cf95b695120f2bbe8cc9fa" ON "organization_profiles" ("primary_contact_email") `);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "role" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "email_verified_at" TIMESTAMP WITH TIME ZONE, "last_login" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_ee66de6cdc53993296d1ceb8aa0" UNIQUE ("email"), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ee66de6cdc53993296d1ceb8aa" ON "accounts" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_bbfc9f3a9ac1993ae4704081f3" ON "accounts" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecd806309a44545de35344424e" ON "accounts" ("status") `);
        await queryRunner.query(`CREATE TABLE "account_email_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" character varying NOT NULL, "otp" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used" boolean NOT NULL DEFAULT false, "accountId" uuid, CONSTRAINT "PK_9c43ceb27a317f6f1be065298e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_095e7a5ccadf954f44e3541825" ON "account_email_verifications" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c3df8bb055df3de1e91788f92" ON "account_email_verifications" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b863a3af25d773a6c1e963186d" ON "account_email_verifications" ("used") `);
        await queryRunner.query(`CREATE TABLE "account_password_resets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" character varying NOT NULL, "token" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used" boolean NOT NULL DEFAULT false, "accountId" uuid, CONSTRAINT "PK_d30fecaa73e9ef126ae40c258a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d56f45c42570c86e4fa32c6a8c" ON "account_password_resets" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_eea0bb52b2b8977679e2c5b416" ON "account_password_resets" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_bdff355e5b3d838f8d3d41a539" ON "account_password_resets" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_adce2c4f210ad0638b3986595d" ON "account_password_resets" ("used") `);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "tier" integer NOT NULL, "account_type" character varying NOT NULL, "amount" bigint NOT NULL, "currency" character varying NOT NULL DEFAULT 'NGN', "interval" character varying NOT NULL DEFAULT 'monthly', "paystack_plan_code" character varying NOT NULL, "description" text NOT NULL, "features" jsonb NOT NULL, "max_incidents" integer, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ae18a0f6e0143f06474aa8cef1" ON "subscription_plans" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa0f49704b17b369c641981806" ON "subscription_plans" ("tier") `);
        await queryRunner.query(`CREATE INDEX "IDX_22d8a15e230621a7267d8dc826" ON "subscription_plans" ("account_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_af2303344b9605e02f943102c2" ON "subscription_plans" ("amount") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ff55b5ac4ffc30a80f31576e2" ON "subscription_plans" ("paystack_plan_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_a119d12fb1daa9ac517698864a" ON "subscription_plans" ("active") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('active', 'expired', 'cancelled', 'past_due')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "account_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "paystack_customer_code" character varying, "paystack_subscription_code" character varying, "paystack_email_token" character varying, "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'active', "current_period_start" TIMESTAMP WITH TIME ZONE NOT NULL, "current_period_end" TIMESTAMP WITH TIME ZONE NOT NULL, "next_billing_date" TIMESTAMP WITH TIME ZONE NOT NULL, "cancel_at_period_end" boolean NOT NULL DEFAULT false, "cancelled_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc328e78eeed6f480bf7b5d588" ON "subscriptions" ("paystack_customer_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb58fb608e5805e61b60e058ea" ON "subscriptions" ("paystack_subscription_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE TABLE "paystack_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "event_type" character varying NOT NULL, "reference" character varying, "paystack_event_id" character varying NOT NULL, "data" jsonb NOT NULL, "processed" boolean NOT NULL DEFAULT false, "processed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f358e4c143cb44dbb3532251479" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b9d700866e61d8ebb5ced3128f" ON "paystack_events" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1b526dfccf35e50db7d0b4010" ON "paystack_events" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_102aa44dea8edbd7ec6cea0ae7" ON "paystack_events" ("paystack_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_664e2d961fa81e2514963c8fe2" ON "paystack_events" ("processed") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_transactions_status_enum" AS ENUM('success', 'failed', 'pending')`);
        await queryRunner.query(`CREATE TABLE "subscription_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now()', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "account_id" uuid NOT NULL, "subscription_id" uuid, "plan_id" uuid, "transaction_reference" character varying NOT NULL, "status" "public"."subscription_transactions_status_enum" NOT NULL DEFAULT 'pending', "amount" bigint NOT NULL, "currency" character varying NOT NULL DEFAULT 'NGN', "payment_method" character varying NOT NULL DEFAULT 'Paystack', "paystack_customer_code" character varying, "metadata" jsonb, CONSTRAINT "UQ_5d8784333156cc5ae42d1a35ab3" UNIQUE ("transaction_reference"), CONSTRAINT "PK_b8a90f16868b06508776988e16e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5d8784333156cc5ae42d1a35ab" ON "subscription_transactions" ("transaction_reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff9d75d352b7b7e8032338039c" ON "subscription_transactions" ("status") `);
        await queryRunner.query(`ALTER TABLE "ticket_sub_category" ADD CONSTRAINT "fk_ticket_category_id" FOREIGN KEY ("category_id") REFERENCES "ticket_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_ticket_created_by_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_ticket_assigned_responder_id" FOREIGN KEY ("assigned_responder_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_ticket_category_id" FOREIGN KEY ("ticket_category_id") REFERENCES "ticket_category"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_ticket_subcategory_id" FOREIGN KEY ("ticket _sub_category_id") REFERENCES "ticket_sub_category"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_lifecycle" ADD CONSTRAINT "FK_ticket_lifecycle_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("ticket_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_lifecycle" ADD CONSTRAINT "FK_e662a6dc2c936f12d5c9c656a2d" FOREIGN KEY ("performed_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "individual_profiles" ADD CONSTRAINT "FK_43bcca0b3b3a7422f9fc7a75479" FOREIGN KEY ("user_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_profiles" ADD CONSTRAINT "FK_762b77719a1ebc06bc35af0296d" FOREIGN KEY ("user_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_email_verifications" ADD CONSTRAINT "FK_11796a5a6dac84270cd4c5a1484" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_password_resets" ADD CONSTRAINT "FK_75a99df0c835d7dc222e3aaf793" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7c7bc85becc85aec89c103784e6" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc" FOREIGN KEY ("plan_id") REFERENCES "subscription_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_transactions" ADD CONSTRAINT "FK_c251d5602982667af00464abe86" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_transactions" ADD CONSTRAINT "FK_87972f688732a2251f2bcd9f886" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_transactions" ADD CONSTRAINT "FK_e34ef910c545a020290baed5f42" FOREIGN KEY ("plan_id") REFERENCES "subscription_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscription_transactions" DROP CONSTRAINT "FK_e34ef910c545a020290baed5f42"`);
        await queryRunner.query(`ALTER TABLE "subscription_transactions" DROP CONSTRAINT "FK_87972f688732a2251f2bcd9f886"`);
        await queryRunner.query(`ALTER TABLE "subscription_transactions" DROP CONSTRAINT "FK_c251d5602982667af00464abe86"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7c7bc85becc85aec89c103784e6"`);
        await queryRunner.query(`ALTER TABLE "account_password_resets" DROP CONSTRAINT "FK_75a99df0c835d7dc222e3aaf793"`);
        await queryRunner.query(`ALTER TABLE "account_email_verifications" DROP CONSTRAINT "FK_11796a5a6dac84270cd4c5a1484"`);
        await queryRunner.query(`ALTER TABLE "organization_profiles" DROP CONSTRAINT "FK_762b77719a1ebc06bc35af0296d"`);
        await queryRunner.query(`ALTER TABLE "individual_profiles" DROP CONSTRAINT "FK_43bcca0b3b3a7422f9fc7a75479"`);
        await queryRunner.query(`ALTER TABLE "ticket_lifecycle" DROP CONSTRAINT "FK_e662a6dc2c936f12d5c9c656a2d"`);
        await queryRunner.query(`ALTER TABLE "ticket_lifecycle" DROP CONSTRAINT "FK_ticket_lifecycle_ticket_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_ticket_subcategory_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_ticket_category_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_ticket_assigned_responder_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_ticket_created_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "ticket_sub_category" DROP CONSTRAINT "fk_ticket_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff9d75d352b7b7e8032338039c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d8784333156cc5ae42d1a35ab"`);
        await queryRunner.query(`DROP TABLE "subscription_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_transactions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_664e2d961fa81e2514963c8fe2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_102aa44dea8edbd7ec6cea0ae7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1b526dfccf35e50db7d0b4010"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9d700866e61d8ebb5ced3128f"`);
        await queryRunner.query(`DROP TABLE "paystack_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb58fb608e5805e61b60e058ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc328e78eeed6f480bf7b5d588"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a119d12fb1daa9ac517698864a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ff55b5ac4ffc30a80f31576e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af2303344b9605e02f943102c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22d8a15e230621a7267d8dc826"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa0f49704b17b369c641981806"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae18a0f6e0143f06474aa8cef1"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_adce2c4f210ad0638b3986595d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdff355e5b3d838f8d3d41a539"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eea0bb52b2b8977679e2c5b416"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d56f45c42570c86e4fa32c6a8c"`);
        await queryRunner.query(`DROP TABLE "account_password_resets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b863a3af25d773a6c1e963186d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c3df8bb055df3de1e91788f92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_095e7a5ccadf954f44e3541825"`);
        await queryRunner.query(`DROP TABLE "account_email_verifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecd806309a44545de35344424e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bbfc9f3a9ac1993ae4704081f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee66de6cdc53993296d1ceb8aa"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5650cf95b695120f2bbe8cc9fa"`);
        await queryRunner.query(`DROP TABLE "organization_profiles"`);
        await queryRunner.query(`DROP TABLE "individual_profiles"`);
        await queryRunner.query(`DROP TABLE "ticket_lifecycle"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TABLE "ticket_category"`);
        await queryRunner.query(`DROP TABLE "ticket_sub_category"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
