export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CALL_AGENT = 'CALL_AGENT',
  CALL_AGENT_MANAGER = 'CALL_AGENT_ADMIN',
  TIER1_RESPONDER_MANAGER = "TIER1_RESPONDER_ADMIN",
  TIER2_RESPONDER_MANAGER = "TIER2_RESPONDER_ADMIN",
  TIER1_RESPONDER = "TIER1_RESPONDER",
  TIER2_RESPONDER = "TIER2_RESPONDER",
}
